### ISSUE TITLE
ImportError: No module named 'phobos'

### ISSUE THREAD

**Issue by karlhm76** [rock-simulation/phobos#108]
Hello.

I am installing on a fresh install of Blender 2.77a 32bit on a windows 7 64 bit system.
I have just downloaded the latest zip file for phobos and followed the installation instructions on the wiki.

I receive the error "No module named 'phobos'" when ticking the button to activate the addon.

I have also attempted to use the 64bit version of Blender with exactly the same result.

![27-06-16 10-10-03 am](https://cloud.githubusercontent.com/assets/20157626/16365869/e4c0dbce-3c4f-11e6-91d1-138688d83d9d.jpg)

Cheers,

Karl.

**Comment by kavonszadkowski** [comment]
Hi Karl,

thanks for indicating this problem. We unfortunately do not have the resources to regularly test Phobos on all platforms with every new release of Blender.

This, though, looks like a purely Python-related problem, since there seems to be no "phobos" subfolder in your "scripts\addons" folder, thus Python cannot be expected to find that package. Guess something went wrong with the unzipping...?

**Comment by karlhm76** [comment]
I'll retry unzipping. I was simply using the windows copy/paste on the zip file.

Thanks for the reply.

**Comment by karlhm76** [comment]
Still no luck at all. 

I used winzip to unzip and rezip the zip file according to the instruction. I will try something else to generate my URDF.


Thanks for your help.

**Comment by kavonszadkowski** [comment]
I'm not sure about the details of zipping and unzipping on Windows in your case, but basically I was implying that the files in the zip folder have to end up in a "scripts\addons\phobos" subfolder, not directly in the "scripts\addons" folder.
