### ISSUE TITLE
Operators should use existing custom properties (read and set in invoke function)

### ISSUE THREAD

**Issue by JanPaul73** [rock-simulation/phobos#39]
This kind of problem probably also happens with other phobos operators:
When selecting a bone that already has joint constraints set and then acivating the "Define joint constraints" operator, the current values of the joint immediately get overwritten by the last values set in the operator. Maybe this is how operators work, however, I think it would be nicer if the current values get read first and can then be adapted only where necessary.

**Comment by kavonszadkowski** [comment]
That is a good point and some operators actually do already behave like that. Eventually, we would like all operators to have that functionality, but unfortunately it has to be programmed in manually. 

Since we have limited resources for the development of Phobos at the moment, such "luxury" functions won't be implemented any time soon. We'd welcome everyone who sends us pull requests with those functions implemented, though.
